import "./globals.css";
import Link from "next/link";
import LoginBtn from "./LoginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LogoutBtn from "./LogoutBtn";
import {cookies} from 'next/headers'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions)
  
  let res = cookies().get('name')
  console.log(res)

  return (
    <html lang="en">
      <body>
      <div className="navbar"> 
        <Link href="/" className="logo">Appleforum</Link> 
        <Link href="/list">List</Link> 
        {/* <LoginBtn /> */}
        {
          session ? <LogoutBtn /> : <LoginBtn />
        }
        <span>🌙</span>
      </div>  
        {children}
      </body>
    </html>
  );
}
