import "./globals.css";
import Link from "next/link";
import LoginBtn from "./LoginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LogoutBtn from "./LogoutBtn";
import {cookies} from 'next/headers'
import DarkMode from "./DarkMode";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions)
  
  let cookieStore = await cookies();
  let res = cookieStore.get('mode')

  return (
    <html lang="en">
      <body className= {res != undefined && res.value == 'dark' ? "dark-mode" : ""}>
      <div className="navbar"> 
        <Link href="/" className="logo">Appleforum</Link> 
        <Link href="/list">List</Link> 
        {
          session ? <LogoutBtn /> : <LoginBtn />
        }
        <DarkMode/>
      </div>  
        {children}
      </body>
    </html>
  );
}
